/*
 * test-6.cpp
 *
 *  Created on: Aug 27, 2015
 *      Author: pavel
 */

#include <iostream>

using namespace std;

int main(int argc, char **argv) {
    try {

    } catch (exception const& e) {
        cerr << e.what() << endl;
    }
}

